//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AreaEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_SPLASH                      102
#define IDB_LIGHTBULB                   103
#define IDD_TIP                         104
#define CG_IDS_TIPOFTHEDAY              105
#define CG_IDS_TIPOFTHEDAYMENU          106
#define CG_IDS_DIDYOUKNOW               107
#define CG_IDS_FILE_ABSENT              108
#define CG_IDP_FILE_CORRUPT             109
#define CG_IDS_TIPOFTHEDAYHELP          110
#define IDS_PROPSHT_CAPTION1            111
#define IDD_SKILLSPAGE1                 112
#define IDD_REGPAGE1                    113
#define IDD_SKILLSPAGE2                 114
#define IDD_SKILLSPAGE3                 115
#define IDD_SKILLSPAGE4                 116
#define CG_IDR_POPUP_AREA_EDITOR_VIEW   117
#define IDR_MAINFRAME                   128
#define IDR_AREAEDTYPE                  129
#define IDD_AREA_NAME                   130
#define IDD_BLANK_ITEM                  131
#define IDD_AUTHOR_NAME                 132
#define IDD_FLAGS                       133
#define IDD_MOBILE                      134
#define IDD_MOBILE_NAME                 135
#define IDD_MOBILE_ACTIONS              136
#define IDD_MOBILE_SUMMARY              137
#define IDD_MOBILE_AFFECT               138
#define IDD_MOBILE_STATS                139
#define IDD_MOBILE_BODY_PARTS           140
#define IDD_MOBILE_RESISTANT            141
#define IDD_MOBILE_ATTACKS              142
#define IDD_MOBILE_DEFENSES             143
#define IDD_MOBILE_SPEAKS               144
#define IDD_MUD_PROGRAM                 145
#define IDD_OBJECT_AFFECT               146
#define IDD_OBJECT_EXTRA_DESCRIPTION    147
#define IDD_OBJECT                      148
#define IDD_OBJECT_NAME                 149
#define IDD_OBJECT_EXTRA_FLAGS          150
#define IDD_OBJECT_SUMMARY              151
#define IDD_OBJECT_STATS                152
#define IDD_ROOM                        153
#define IDD_ROOM_EXIT                   154
#define IDD_OBJECT_ROOM_MAP             155
#define IDD_ROOM_NAME                   156
#define IDD_ROOM_SUMMARY                157
#define IDD_ROOM_FLAGS                  158
#define IDD_RESETS                      159
#define IDD_REGPAGE4                    160
#define IDD_REGPAGE5                    161
#define IDD_REGPAGE6                    162
#define IDD_REGPAGE7                    163
#define IDD_REGPAGE8                    164
#define IDD_REGPAGE9                    165
#define IDD_REGPAGE10                   166
#define IDD_REGPAGE11                   167
#define IDD_REGPAGE12                   168
#define IDD_REGPAGE13                   169
#define IDD_REGPAGE14                   170
#define IDD_REGPAGE15                   171
#define IDD_REGPAGE16                   172
#define IDD_CHOOSE_MOB                  173
#define IDD_DOCUMENT_INFO               174
#define IDD_ADD_TO_OBJECT               175
#define IDD_CREDITS                     176
#define IDR_CREDITS                     177
#define IDR_NON_MENU                    178
#define IDD_EDIT                        179
#define IDD_EDIT_COMMAND                180
#define IDD_PREFERENCES                 181
#define IDD_DELETE_REFERENCES           182
#define IDD_RENUMBER                    183
#define IDB_LOGO                        184
#define IDD_WEAR_FLAGS                  185
#define IDD_PREFSP1                     186
#define IDD_NEIGHBOUR_NAME              188
#define IDD_WALKTHROUGH                 189
#define IDD_FIND                        190
#define CG_IDD_PROGRESS                 191
#define CG_IDS_PROGRESS_CAPTION         192
#define IDD_AREA_TYPE                   193
#define ID_PROBLEMS_LOADING_AREA        195
#define IDD_WELCOME                     196
#define IDD_WELCOME1                    197
#define IDD_UNREGISTERED_DELAY          198
#define IDD_REGPAGE2                    199
#define IDD_REGPAGE3                    200
#define IDD_SHOP                        201
#define IDD_REPAIR                      202
#define IDD_HELP                        203
#define IDD_CHOOSE_ROOM                 204
#define IDD_CHOOSE_OBJECT               205
#define IDD_CHOOSE_EXIT                 206
#define IDD_ADD_TO_ROOM                 207
#define IDD_MOBILE_RESETS               208
#define IDD_OBJECT_RESETS               209
#define IDD_CHOOSE_SPELL                210
#define IDD_SKILLS_LIST                 211
#define IDD_COMMANDS_LIST               212
#define IDD_SOCIALS_LIST                213
#define IDD_EDIT_SOCIAL                 214
#define IDD_PREFSP2                     215
#define IDD_PREFSP3                     216
#define IDD_GENERAL_FLAGS               217
#define IDD_AREA                        218
#define IDD_AREA_RANGES                 219
#define IDD_AREA_VNUMS                  220
#define IDD_AREA_NEIGHBOUR              221
#define IDD_AREA_CLIMATE                222
#define IDD_ADD_EXIT                    223
#define IDD_FIND_IN_DIALOG              224
#define IDD_ROOM1                       225
#define IDD_ROOM_EXIT_DETAILS           226
#define IDD_CHOOSE_FROM_LIST            227
#define IDD_CHOOSE_FLAGS                228
#define IDD_SELECT_FROM_LIST            229
#define IDD_GENERATED_NAME              230
#define IDD_GOTO_VNUM                   231
#define IDD_PREFSP4                     232
#define IDD_SPELL_CHECK                 233
#define IDD_AFFECT_EDIT                 245
#define IDR_LICENSE                     246
#define ID_IGNORE_BTN                   1001
#define ID_LEX_CONTENTS_CB              1001
#define ID_IGNORE_ALL_BTN               1002
#define ID_LEX_FILES_CB                 1002
#define ID_CHANGE_BTN                   1003
#define ID_LEX_ADD_FILE_BTN             1003
#define ID_CHANGE_ALL_BTN               1004
#define ID_LEX_DEL_FILE_BTN             1004
#define ID_ADD_TO_LEX_BTN               1005
#define ID_SUGGEST_BTN                  1006
#define ID_UNDO_BTN                     1007
#define ID_SUGGEST_LIST                 1009
#define ID_PROBLEM_LBL                  1011
#define ID_PROBLEM_WORD_EDT             1012
#define ID_IGN_LEX_CB                   1013
#define ID_EDIT_LEX_BTN                 1014
#define ID_LEX_ADD_WORD_BTN             1014
#define ID_LEX_DEL_WORD_BTN             1015
#define ID_LEX_NEW_FILE_BTN             1016
#define IDC_IGNORE_CAPS_CHK             1021
#define IDC_REPORT_DOUBLED_WORDS_CHK    1022
#define ID_LANGUAGE_CB                  1023
#define ID_IMPORT_BTN                   1024
#define ID_EXPORT_BTN                   1025
#define IDC_IGNORE_MIXED_DIGITS_CHK     1025
#define ID_FILE_NAME_EDIT               1027
#define ID_BROWSE_BTN                   1028
#define IDC_IGNORE_ALL_CAPS_CHK         1028
#define ID_LANG_TEXT                    1029
#define ID_OPTIONS_BTN                  1031
#define ID_SUGGESTIONS_LBL              1033
#define ID_ADD_WORDS_LBL                1034
#define ID_WORDS_LBL                    1035
#define ID_FILES_LBL                    1036
#define ID_LANGUAGE_LBL                 1037
#define ID_FILE_NAME_LBL                1039
#define IDC_CASE_SENSITIVE_CHK          1041
#define IDC_PHONETIC_SUGG_CHK           1042
#define IDC_SUGGEST_SPLIT_WORDS_CHK     1043
#define IDC_IGNORE_MIXED_CASE_CHK       1044
#define IDC_TYPO_SUGG_CHK               1045
#define IDC_IGNORE_DOMAIN_NAMES_CHK     1046
#define IDC_CONTEXT_EDT                 1050
#define IDC_AUTO_CORRECT_CHK            1050
#define IDC_SUGG_DEPTH_LOW_RB           1051
#define IDC_SUGG_DEPTH_MED_RB           1052
#define IDC_SUGG_DEPTH_HI_RB            1053
#define ID_HELP_BTN                     1055
#define ID_LEX_OTHER_WORD_EDT           1057
#define ID_LEX_ACTION_CB                1058
#define IDC_DICT_LANG_CBO               1059
#define IDC_AREA_NAME                   2000
#define IDC_BULB                        2001
#define IDC_AUTHOR_NAME                 2002
#define IDC_STARTUP                     2003
#define CG_IDC_PROGDLG_PROGRESS         2003
#define IDC_RESET_MESSAGE               2004
#define CG_IDC_PROGDLG_PERCENT          2004
#define IDC_PLAYER_KILL_ALLOWED         2005
#define CG_IDC_PROGDLG_STATUS           2005
#define IDC_NEXTTIP                     2006
#define IDC_RESET_FREQUENCY             2007
#define IDC_NAME                        2008
#define IDC_TIPSTRING                   2009
#define IDC_AUTHOR                      2010
#define IDC_SHORT_DESCRIPTION           2011
#define IDC_FILENAME                    2012
#define IDC_LONG_DESCRIPTION            2013
#define IDC_FLAGS                       2014
#define IDC_SLOT                        2015
#define IDC_RANGES                      2015
#define IDC_DESCRIPTION                 2016
#define IDC_VNUMS                       2016
#define IDC_TARGET                      2017
#define IDC_SUMMARY                     2017
#define IDC_MOBILE_TABS                 2018
#define IDC_KEYWORD                     2019
#define IDC_MINIMUM_POSITION            2020
#define IDC_ACT_IS_NPC                  2021
#define IDC_MIN_MANA                    2022
#define IDC_ACT_SENTINEL                2023
#define IDC_BEATS                       2024
#define IDC_ACT_SCAVENGER               2025
#define IDC_GUILD                       2026
#define IDC_ACT_AGGRESSIVE              2027
#define IDC_ACTIONS                     2028
#define IDC_MIN_LEVEL                   2029
#define IDC_ACT_STAY_AREA               2030
#define IDC_VNUM                        2031
#define IDC_SELECTED_LIST               2031
#define IDC_RANGE                       2032
#define IDC_AVAILABLE_LIST              2032
#define IDC_ACT_WIMPY                   2033
#define IDC_INSERT                      2033
#define IDC_AFFECTEDBY                  2034
#define IDC_TELE_VNUM                   2035
#define IDC_X                           2036
#define IDC_INFO                        2037
#define IDC_ACT_PET                     2038
#define IDC_TELE_DELAY                  2039
#define IDC_Y                           2040
#define IDC_ACT_TRAIN                   2041
#define IDC_ENTRY                       2042
#define IDC_ACT_PRACTICE                2043
#define IDC_ACT_IMMORTAL                2044
#define IDC_ACT_DEADLY                  2045
#define IDC_ACT_POLYSELF                2046
#define IDC_ACT_META_AGGR               2047
#define IDC_ACT_GUARDIAN                2048
#define IDC_ACT_RUNNING                 2049
#define IDC_ACT_NOWANDER                2050
#define IDC_ACT_MOUNTABLE               2051
#define IDC_ACT_MOUNTED                 2052
#define IDC_ACT_SCHOLAR                 2053
#define IDC_ACT_SECRETIVE               2054
#define IDC_ACT_POLYMORPHED             2055
#define IDC_ACT_MOBINVIS                2056
#define IDC_ACT_NOASSIST                2057
#define IDC_ACT_PROTOTYPE               2058
#define IDC_AFF_BLIND                   2059
#define IDC_AFF_INVISIBLE               2060
#define IDC_AFF_DETECT_EVIL             2061
#define IDC_AFF_DETECT_INVIS            2062
#define IDC_AFF_DETECT_MAGIC            2063
#define IDC_AFF_DETECT_HIDDEN           2064
#define IDC_AFF_HOLD                    2065
#define IDC_AFF_SANCTUARY               2066
#define IDC_AFF_FAERIE_FIRE             2067
#define IDC_AFF_INFRARED                2068
#define IDC_AFF_CURSE                   2069
#define IDC_AFF_FLAMING                 2070
#define IDC_AFF_POISON                  2071
#define IDC_AFF_PROTECT                 2072
#define IDC_AFF_PARALYSIS               2073
#define IDC_AFF_SNEAK                   2074
#define IDC_AFF_HIDE                    2075
#define IDC_AFF_SLEEP                   2076
#define IDC_AFF_CHARM                   2077
#define IDC_AFF_FLYING                  2078
#define IDC_AFF_PASS_DOOR               2079
#define IDC_AFF_FLOATING                2080
#define IDC_AFF_TRUESIGHT               2081
#define IDC_AFF_DETECTTRAPS             2082
#define IDC_AFF_SCRYING                 2083
#define IDC_LEVEL                       2084
#define IDC_AFF_FIRESHIELD              2085
#define IDC_MATERIAL                    2085
#define IDC_SEX                         2086
#define IDC_AFF_SHOCKSHIELD             2087
#define IDC_STATS                       2088
#define IDC_AFF_HAUS1                   2089
#define IDC_VALUES                      2089
#define IDC_STR                         2090
#define IDC_BODYPARTS                   2091
#define IDC_AFF_ICESHIELD               2092
#define IDC_ATTACKS                     2093
#define IDC_AFF_POSSESS                 2094
#define IDC_INT                         2095
#define IDC_DEFENSES                    2096
#define IDC_AFF_BERSERK                 2097
#define IDC_WIS                         2098
#define IDC_RESISTANT                   2099
#define IDC_AFF_AQUA_BREATH             2100
#define IDC_CON                         2101
#define IDC_RADIO2                      2102
#define IDC_IMMUNE                      2103
#define IDC_WEAR2                       2103
#define IDC_DEX                         2104
#define IDC_WEAR8                       2104
#define IDC_RADIO3                      2105
#define IDC_SUSCEPTIBLE                 2106
#define IDC_WEAR4                       2106
#define IDC_CHA                         2107
#define IDC_WEAR5                       2107
#define IDC_SPEAKS                      2108
#define IDC_WEAR6                       2108
#define IDC_LCK                         2109
#define IDC_WEAR9                       2109
#define IDC_AVERAGE                     2109
#define IDC_SPEAKING                    2110
#define IDC_WEAR10                      2110
#define IDC_ALIGNMENT                   2111
#define IDC_WEAR11                      2111
#define IDC_MOBTHAC0                    2112
#define IDC_WEAR12                      2112
#define IDC_AC                          2113
#define IDC_WEAR13                      2113
#define IDC_HITNODICE                   2114
#define IDC_WEAR15                      2114
#define IDC_HITSIZEDICE                 2115
#define IDC_WEAR16                      2115
#define IDC_HITPLUS                     2116
#define IDC_WEAR17                      2116
#define IDC_GOLD                        2117
#define IDC_WEAR18                      2117
#define IDC_DAMNODICE                   2118
#define IDC_WEAR19                      2118
#define IDC_DAMSIZEDICE                 2119
#define IDC_WEAR20                      2119
#define IDC_DAMPLUS                     2120
#define IDC_WEAR21                      2120
#define IDC_EXP                         2121
#define IDC_SAVING_POISON_DEATH         2122
#define IDC_SAVING_WAND                 2123
#define IDC_SAVING_PARA_PETRI           2124
#define IDC_SELECT1                     2124
#define IDC_SAVING_BREATH               2125
#define IDC_SAVING_SPELL_STAFF          2126
#define IDC_SELECT2                     2126
#define IDC_RACE                        2127
#define IDC_SELECT3                     2127
#define IDC_CLASS                       2128
#define IDC_SELECT4                     2128
#define IDC_HEIGHT                      2129
#define IDC_SELECT5                     2129
#define IDC_WEIGHT                      2130
#define IDC_SELECT6                     2130
#define IDC_POSITION                    2131
#define IDC_SELECT7                     2131
#define IDC_HEAD                        2132
#define IDC_MANANODICE                  2132
#define IDC_SELECT8                     2132
#define IDC_DEFPOSITION                 2133
#define IDC_SELECT9                     2133
#define IDC_NUMATTACKS                  2134
#define IDC_ARMS                        2135
#define IDC_MANASIZEDICE                2135
#define IDC_LOG                         2136
#define IDC_MANAPLUS                    2136
#define IDC_HITROLL                     2137
#define IDC_LEGS                        2138
#define IDC_DAMROLL                     2139
#define IDC_HEART                       2140
#define IDC_BRAINS                      2141
#define IDC_GUTS                        2142
#define IDC_HANDS                       2143
#define IDC_FEET                        2144
#define IDC_FINGERS                     2145
#define IDC_EAR                         2146
#define IDC_EYE                         2147
#define IDC_LONG_TONGUE                 2148
#define IDC_EYESTALKS                   2149
#define IDC_TENTACLES                   2150
#define IDC_FINS                        2151
#define IDC_WINGS                       2152
#define IDC_FONT_NAME                   2153
#define IDC_TAIL                        2154
#define IDC_SCALES                      2155
#define IDC_CLAWS                       2156
#define IDC_FANGS                       2157
#define IDC_HORNS                       2158
#define IDC_TUSKS                       2159
#define IDC_YES_NO                      2160
#define IDC_TAILATTACK                  2161
#define IDC_USER_NAME                   2162
#define IDC_SHARPSCALES                 2163
#define IDC_PERSONAL_CODE               2164
#define IDC_BEAK                        2165
#define IDC_EMAIL_ADDRESS               2166
#define IDC_HAUNCH                      2167
#define IDC_POSTAL_ADDRESS              2168
#define IDC_HOOVES                      2169
#define IDC_ZIP_CODE                    2170
#define IDC_PAWS                        2171
#define IDC_COUNTRY                     2172
#define IDC_FORELEGS                    2173
#define IDC_CREDIT_CARD_NUMBER          2174
#define IDC_FEATHERS                    2175
#define IDC_EXPIRY_DATE                 2176
#define IDC_BITE                        2177
#define IDC_NAME_ON_CARD                2178
#define IDC_STING                       2179
#define IDC_REGISTER                    2180
#define IDC_REGISTER_NOW                2181
#define IDC_PUNCH                       2182
#define IDC_KICK                        2183
#define IDC_PROGRESS_BAR                2184
#define IDC_TRIP                        2185
#define IDC_MASTERCARD                  2186
#define IDC_BASH                        2187
#define IDC_REGISTRATION_CODE           2188
#define IDC_VISA                        2189
#define IDC_STUN                        2190
#define IDC_PHONE_NUMBER                2191
#define IDC_CHEQUE                      2192
#define IDC_GOUGE                       2193
#define IDC_FAX_NUMBER                  2194
#define IDC_CASH                        2195
#define IDC_BACKSTAB                    2196
#define IDC_POSTAL_ORDER                2197
#define IDC_CC_LABEL                    2198
#define IDC_FEED                        2199
#define IDC_DRAIN                       2200
#define IDC_FIREBREATH                  2201
#define IDC_DRAIN2                      2202
#define IDC_FROSTBREATH                 2203
#define IDC_DRAIN3                      2204
#define IDC_ACIDBREATH                  2205
#define IDC_LIGHTNBREATH                2206
#define IDC_GASBREATH                   2207
#define IDC_POISON                      2208
#define IDC_NASTYPOISON                 2209
#define IDC_POISON2                     2210
#define IDC_GAZE                        2211
#define IDC_POISON3                     2212
#define IDC_BLINDNESS                   2213
#define IDC_CAUSESERIOUS                2214
#define IDC_EARTHQUAKE                  2215
#define IDC_CAUSECRITICAL               2216
#define IDC_CURSE                       2217
#define IDC_FLAMESTRIKE                 2218
#define IDC_HARM                        2219
#define IDC_FIREBALL                    2220
#define IDC_COLORSPRAY                  2221
#define IDC_WEAKEN                      2222
#define IDC_SPIRALBLAST                 2223
#define IDC_PARRY                       2224
#define IDC_DODGE                       2225
#define IDC_HEAL                        2226
#define IDC_CURELIGHT                   2227
#define IDC_CURESERIOUS                 2228
#define IDC_CURECRITICAL                2229
#define IDC_DISPELMAGIC                 2230
#define IDC_DISPELEVIL                  2231
#define IDC_SANCTUARY                   2232
#define IDC_FIRESHIELD                  2233
#define IDC_SHOCKSHIELD                 2234
#define IDC_SHIELD                      2235
#define IDC_BLESS                       2236
#define IDC_STONESKIN                   2237
#define IDC_TELEPORT                    2238
#define IDC_MONSUM1                     2239
#define IDC_MONSUM2                     2240
#define IDC_MONSUM3                     2241
#define IDC_MONSUM4                     2242
#define IDC_DISARM                      2243
#define IDC_ICESHIELD                   2244
#define IDC_GRIP                        2245
#define IDC_FIRE                        2246
#define IDC_COLD                        2247
#define IDC_ELECTRICITY                 2248
#define IDC_ENERGY                      2249
#define IDC_TOP_MARGIN                  2250
#define IDC_BLUNT                       2251
#define IDC_LEFT_MARGIN                 2252
#define IDC_PIERCE                      2253
#define IDC_FONT                        2254
#define IDC_SLASH                       2255
#define IDC_LINES_PER_PAGE              2256
#define IDC_ACID                        2257
#define IDC_SLEEP                       2258
#define IDC_CHARM                       2259
#define IDC_HOLD                        2260
#define IDC_NONMAGIC                    2261
#define IDC_DUAL_WIELD                  2262
#define IDC_PLUS1                       2263
#define IDC_PLUS2                       2264
#define IDC_PLUS3                       2265
#define IDC_PLUS4                       2266
#define IDC_PLUS5                       2267
#define IDC_PLUS6                       2268
#define IDC_MAGIC                       2269
#define IDC_PARALYSIS                   2270
#define IDC_FIRE2                       2271
#define IDC_COMMON                      2272
#define IDC_COLD2                       2273
#define IDC_ELVEN                       2274
#define IDC_ELECTRICITY2                2275
#define IDC_DWARVEN                     2276
#define IDC_ENERGY2                     2277
#define IDC_PIXIE                       2278
#define IDC_BLUNT2                      2279
#define IDC_OGRE                        2280
#define IDC_PIERCE2                     2281
#define IDC_ORCISH                      2282
#define IDC_SLASH2                      2283
#define IDC_TROLLISH                    2284
#define IDC_ACID2                       2285
#define IDC_RODENT                      2286
#define IDC_SLEEP2                      2287
#define IDC_INSECTOID                   2288
#define IDC_CHARM2                      2289
#define IDC_MAMMAL                      2290
#define IDC_HOLD2                       2291
#define IDC_REPTILE                     2292
#define IDC_NONMAGIC2                   2293
#define IDC_DRAGON                      2294
#define IDC_PLUS7                       2295
#define IDC_SPIRITUAL                   2296
#define IDC_PLUS8                       2297
#define IDC_MAGICAL                     2298
#define IDC_PLUS9                       2299
#define IDC_GOBLIN                      2300
#define IDC_PLUS10                      2301
#define IDC_GOD                         2302
#define IDC_PLUS11                      2303
#define IDC_ANCIENT                     2304
#define IDC_PLUS12                      2305
#define IDC_HALFLING                    2306
#define IDC_MATCH_CASE                  2307
#define IDC_MAGIC2                      2308
#define IDC_CLAN                        2309
#define IDC_PARALYSIS2                  2310
#define IDC_GITH                        2311
#define IDC_FIRE3                       2312
#define IDC_COMMON2                     2313
#define IDC_PROGRAM_TYPE                2314
#define IDC_COLD3                       2315
#define IDC_ELVEN2                      2316
#define IDC_CLICK_MESSAGE               2316
#define IDC_ARGLIST                     2317
#define IDC_ELECTRICITY3                2318
#define IDC_DWARVEN2                    2319
#define IDC_COMLIST                     2320
#define IDC_OBJECT_TABS                 2321
#define IDC_ENERGY3                     2322
#define IDC_PIXIE2                      2323
#define IDC_MODIFIER                    2324
#define IDC_BLUNT3                      2325
#define IDC_DURATION                    2325
#define IDC_OGRE2                       2326
#define IDC_LOCATION                    2327
#define IDC_PIERCE3                     2328
#define IDC_AFFECT_TYPE                 2328
#define IDC_ORCISH2                     2329
#define IDC_GLOW                        2330
#define IDC_SLASH3                      2331
#define IDC_TROLLISH2                   2332
#define IDC_HUM                         2333
#define IDC_ACID3                       2334
#define IDC_RODENT2                     2335
#define IDC_DARK                        2336
#define IDC_SLEEP3                      2337
#define IDC_INSECTOID2                  2338
#define IDC_LOYAL                       2339
#define IDC_CHARM3                      2340
#define IDC_MAMMAL2                     2341
#define IDC_EVIL                        2342
#define IDC_HOLD3                       2343
#define IDC_REPTILE2                    2344
#define IDC_INVIS                       2345
#define IDC_NONMAGIC3                   2346
#define IDC_DRAGON2                     2347
#define IDC_NODROP                      2348
#define IDC_PLUS13                      2349
#define IDC_SPIRITUAL2                  2350
#define IDC_ANTI_GOOD                   2351
#define IDC_PLUS14                      2352
#define IDC_MAGICAL2                    2353
#define IDC_ANTI_EVIL                   2354
#define IDC_PLUS15                      2355
#define IDC_GOBLIN2                     2356
#define IDC_ANTI_NEUTRAL                2357
#define IDC_PLUS16                      2358
#define IDC_GOD2                        2359
#define IDC_NOREMOVE                    2360
#define IDC_PLUS17                      2361
#define IDC_ANCIENT2                    2362
#define IDC_INVENTORY                   2363
#define IDC_PLUS18                      2364
#define IDC_HALFLING2                   2365
#define IDC_ANTI_MAGE                   2366
#define IDC_MAGIC3                      2367
#define IDC_CLAN2                       2368
#define IDC_ANTI_THIEF                  2369
#define IDC_PARALYSIS3                  2370
#define IDC_GITH2                       2371
#define IDC_ANTI_WARRIOR                2372
#define IDC_ANTI_CLERIC                 2373
#define IDC_ORGANIC                     2374
#define IDC_METAL                       2375
#define IDC_DONATION                    2376
#define IDC_CLANOBJECT                  2377
#define IDC_CLANCORPSE                  2378
#define IDC_ANTI_VAMPIRE                2379
#define IDC_ANTI_DRUID                  2380
#define IDC_HIDDEN                      2381
#define IDC_POISONED                    2382
#define IDC_ERROR_LIST                  2383
#define IDC_COVERING                    2384
#define IDC_DEATHROT                    2385
#define IDC_BURIED                      2386
#define IDC_PROTOTYPE                   2387
#define IDC_FORM_TYPE                   2388
#define IDC_TYPE                        2389
#define IDC_PRINT                       2390
#define IDC_EXTRA_FLAGS                 2391
#define IDC_SAVE                        2392
#define IDC_WEAR_FLAGS                  2393
#define IDC_VERSION_LABEL               2394
#define IDC_VALUE_MEANINGS              2394
#define IDC_ACTION                      2395
#define IDC_AFFECTS                     2396
#define IDC_REGISTERED_USER             2397
#define IDC_COST                        2398
#define IDC_SECTOR_TYPE                 2399
#define IDC_POWER                       2400
#define IDC_VALUE1                      2401
#define IDC_NO_MOB                      2402
#define IDC_FUNCTION                    2403
#define IDC_DEATH                       2404
#define IDC_INDOORS                     2405
#define IDC_LAWFUL                      2406
#define IDC_VALUE2                      2407
#define IDC_NEUTRAL                     2408
#define IDC_VALUE3                      2409
#define IDC_CHAOTIC                     2410
#define IDC_VALUE4                      2411
#define IDC_NO_MAGIC                    2412
#define IDC_VALUE5                      2413
#define IDC_TUNNEL                      2414
#define IDC_VALUE6                      2415
#define IDC_PRIVATE                     2416
#define IDC_LAYERS                      2417
#define IDC_SAFE                        2418
#define IDC_RENT                        2419
#define IDC_SOLITARY                    2420
#define IDC_CONDITION                   2420
#define IDC_PET_SHOP                    2421
#define IDC_NO_RECALL                   2422
#define IDC_NODROPALL                   2423
#define IDC_SILENCE                     2424
#define IDC_LOGSPEECH                   2425
#define IDC_CLANSTOREROOM               2426
#define IDC_NO_SUMMON                   2427
#define IDC_SPIN_TOP_MARGIN             2428
#define IDC_NO_ASTRAL                   2429
#define IDC_SPIN_LEFT_MARGIN            2430
#define IDC_TELESHOWDESC                2431
#define IDC_SPIN_LINES_PER_PAGE         2432
#define IDC_NOFLOOR                     2433
#define IDC_EXIT_TO                     2434
#define IDC_EXIT_TO_DESCRIPTION         2435
#define IDC_ISDOOR                      2436
#define IDC_KEY_DESCRIPTION             2436
#define IDC_CLOSED                      2437
#define IDC_LOCKED                      2438
#define IDC_SECRET                      2439
#define IDC_SWIM                        2440
#define IDC_PICKPROOF                   2441
#define IDC_FLY                         2442
#define IDC_CLIMB                       2443
#define IDC_DIG                         2444
#define IDC_KEY                         2445
#define IDC_WEB_ADDRESS                 2446
#define IDC_NOPASSDOOR                  2447
#define IDC_PASSAGE                     2448
#define IDC_PORTAL                      2449
#define IDC_DISTANCE                    2450
#define IDC_XCLIMB                      2451
#define IDC_XENTER                      2452
#define IDC_XLEAVE                      2453
#define IDC_XAUTO                       2454
#define IDC_XSEARCHABLE                 2455
#define IDC_BASHED                      2456
#define IDC_MESSAGE                     2457
#define IDC_BASHPROOF                   2458
#define IDC_MESSAGE1                    2459
#define IDC_NOMOB                       2460
#define IDC_MESSAGE2                    2461
#define IDC_CHANGES_ADDRESS             2462
#define IDC_WINDOW                      2463
#define IDC_XLOOK                       2464
#define IDC_DIRECTION                   2465
#define IDC_RADIO4                      2466
#define IDC_RADIO5                      2467
#define IDC_RADIO6                      2468
#define IDC_RADIO7                      2469
#define IDC_RADIO8                      2470
#define IDC_RADIO9                      2471
#define IDC_RADIO10                     2472
#define IDC_RADIO11                     2473
#define IDC_MOBILE_BUTTON               2474
#define IDC_ARG1                        2475
#define IDC_ARG2                        2476
#define IDC_ARG3                        2477
#define IDC_LABEL_ARG1                  2478
#define IDC_LABEL_ARG2                  2479
#define IDC_LABEL_EXTRA                 2480
#define IDC_EXTRA                       2481
#define IDC_LABEL_ARG3                  2482
#define IDC_DESC_ARG1                   2483
#define IDC_DESC_ARG2                   2484
#define IDC_DESC_ARG3                   2485
#define IDC_DESC_EXTRA                  2486
#define IDC_OBJECT_BUTTON               2487
#define IDC_GIVE_BUTTON                 2488
#define IDC_EQUIP_BUTTON                2489
#define IDC_PUT_BUTTON                  2490
#define IDC_DOOR_BUTTON                 2491
#define IDC_RAND_BUTTON                 2492
#define IDC_TRAP_BUTTON                 2493
#define IDC_HIDE_BUTTON                 2494
#define IDC_TAKE                        2495
#define IDC_LABEL_ARG4                  2495
#define IDC_WEAR_FINGER                 2496
#define IDC_ARG4                        2496
#define IDC_WEAR_NECK                   2497
#define IDC_DESC_ARG4                   2497
#define IDC_WEAR_BODY                   2498
#define IDC_WEAR_HEAD                   2499
#define IDC_WEAR_LEGS                   2500
#define IDC_WEAR_FEET                   2501
#define IDC_WEAR_HANDS                  2502
#define IDC_WEAR_ARMS                   2503
#define IDC_WEAR_SHIELD                 2504
#define IDC_WEAR_ABOUT                  2505
#define IDC_WEAR_WAIST                  2506
#define IDC_WEAR_WRIST                  2507
#define IDC_WIELD                       2508
#define IDC_CHECK1                      2509
#define IDC_SHOW_FLAG_NUMBERS           2509
#define IDC_SHOW_PROGRAMS               2509
#define IDC_MAKE_REVERSE                2509
#define IDC_SHOW_VNUMS                  2509
#define IDC_AUSTRALIAN                  2509
#define IDC_ALL_AREAS                   2509
#define IDC_ENABLE                      2509
#define IDC_WATER                       2510
#define IDC_MOB_COMPACT                 2511
#define IDC_SHOW_WARNINGS               2512
#define IDC_POSSESSED                   2513
#define IDC_PRINT_TO_FILE               2514
#define IDC_FLAG1                       2515
#define IDC_WEAR_EARS                   2516
#define IDC_KEEPER                      2517
#define IDC_EARTH                       2518
#define IDC_ROOM_COMPACT                2519
#define IDC_FLAG2                       2520
#define IDC_WEAR_EYES                   2521
#define IDC_BUY_TYPE1                   2522
#define IDC_AIR                         2523
#define IDC_OBJECT_COMPACT              2524
#define IDC_FLAG3                       2525
#define IDC_MISSILE_WIELD               2526
#define IDC_BUY_TYPE2                   2527
#define IDC_ASTRAL                      2528
#define IDC_FLAG4                       2529
#define IDC_BUY_TYPE3                   2530
#define IDC_AREA                        2531
#define IDC_FLAG5                       2532
#define IDC_BUY_TYPE4                   2533
#define IDC_DISTANT                     2534
#define IDC_FLAG6                       2535
#define IDC_BUY_TYPE5                   2536
#define IDC_REVERSE                     2537
#define IDC_FLAG7                       2538
#define IDC_PROFIT_BUY                  2539
#define IDC_SAVE_HALF_DAMAGE            2540
#define IDC_FLAG8                       2541
#define IDC_OPEN_HOUR                   2542
#define IDC_SAVE_NEGATES                2543
#define IDC_FLAG9                       2544
#define IDC_KEEPER_DESCRIPTION          2545
#define IDC_ACCUMULATIVE                2546
#define IDC_FLAG10                      2547
#define IDC_CLOSE_HOUR                  2548
#define IDC_RECASTABLE                  2549
#define IDC_FLAG11                      2550
#define IDC_PROFIT_SELL                 2551
#define IDC_NOSCRIBE                    2552
#define IDC_FLAG12                      2553
#define IDC_PROFIT_FIX                  2554
#define IDC_NOBREW                      2555
#define IDC_FLAG13                      2556
#define IDC_SHOP_TYPE                   2557
#define IDC_GROUPSPELL                  2558
#define IDC_FLAG14                      2559
#define IDC_FIX_TYPE1                   2560
#define IDC_OBJECT                      2561
#define IDC_FLAG15                      2562
#define IDC_FIX_TYPE2                   2563
#define IDC_CHARACTER                   2564
#define IDC_FLAG16                      2565
#define IDC_FIX_TYPE3                   2566
#define IDC_SECRETSKILL                 2567
#define IDC_FLAG17                      2568
#define IDC_LOW_SOFT_RANGE              2569
#define IDC_PKSENSITIVE                 2570
#define IDC_AREA_VERSION                2570
#define IDC_REPAIR_TYPE                 2571
#define IDC_FLAG18                      2572
#define IDC_HIGH_SOFT_RANGE             2573
#define IDC_STOPONFAIL                  2574
#define IDC_FLAG19                      2575
#define IDC_LOW_HARD_RANGE              2576
#define IDC_KEYWORDS                    2577
#define IDC_FLAG20                      2578
#define IDC_HIGH_HARD_RANGE             2579
#define IDC_TEXT                        2580
#define IDC_FLAG21                      2581
#define IDC_LOW_ECONOMY                 2582
#define IDC_ARG1_CHOOSE                 2583
#define IDC_FLAG22                      2584
#define IDC_HIGH_ECONOMY                2585
#define IDC_ARG1_GOTO                   2586
#define IDC_FLAG23                      2587
#define IDC_MOB_LIST                    2588
#define IDC_ARG2_CHOOSE                 2589
#define IDC_FLAG24                      2590
#define IDC_ROOM_LIST                   2591
#define IDC_ARG2_GOTO                   2592
#define IDC_FLAG25                      2593
#define IDC_ARG3_CHOOSE                 2594
#define IDC_OBJECT_LIST                 2595
#define IDC_FLAG26                      2596
#define IDC_ARG3_GOTO                   2597
#define IDC_EXIT_LIST                   2598
#define IDC_FLAG27                      2599
#define IDC_CHOOSE                      2600
#define IDC_FLAG28                      2601
#define IDC_GOTO                        2602
#define IDC_FLAG29                      2603
#define IDC_GOTO_KEY                    2603
#define IDC_ENTRANCES                   2604
#define IDC_FLAG30                      2605
#define IDC_GOTO_ENTRANCE               2606
#define IDC_FLAG31                      2607
#define IDC_ADD_EXIT                    2607
#define IDC_OBJECTS                     2608
#define IDC_MOB_LOW_VNUM                2609
#define IDC_FLAG32                      2610
#define IDC_GOTO_OBJECT                 2611
#define IDC_MOB_HIGH_VNUM               2612
#define IDC_HELPS                       2613
#define IDC_FLAG33                      2614
#define IDC_MOBILES                     2615
#define IDC_OBJ_LOW_VNUM                2616
#define IDC_FLAG34                      2617
#define IDC_OBJ_HIGH_VNUM               2618
#define IDC_SPEC_FUN                    2619
#define IDC_MOBILE_PROGRAMS             2620
#define IDC_FLAG35                      2621
#define IDC_ROOM_LOW_VNUM               2622
#define IDC_RESETS                      2623
#define IDC_ADD_BUTTONS                 2624
#define IDC_FLAG36                      2625
#define IDC_ROOM_HIGH_VNUM              2626
#define IDC_ROOMS                       2627
#define IDC_RADIO1                      2628
#define IDC_FLAG37                      2629
#define IDC_SHOPS                       2630
#define IDC_OBJECT_LOW_VNUM             2631
#define IDC_FLAG38                      2632
#define IDC_REPAIRS                     2633
#define IDC_CREDITS                     2634
#define IDC_OBJECT_HIGH_VNUM            2635
#define IDC_LICENSE                     2635
#define IDC_CREDITS_LIST                2636
#define IDC_ROOM_EXITS                  2637
#define IDC_ROOM_PROGRAMS               2638
#define IDC_EDIT_TEXT                   2639
#define IDC_OBJECT_AFFECTS              2640
#define IDC_EDIT_DESCRIPTION            2641
#define IDC_OBJECT_PROGRAMS             2642
#define IDC_EDIT_HELP                   2643
#define IDC_LOADED                      2644
#define IDC_GOTO_RESET                  2645
#define IDC_TELEPORT_CHOOSE             2646
#define IDC_TELEPORT_GOTO               2647
#define IDC_DESC_TELEPORT               2648
#define IDC_DESC_VALUE1                 2649
#define IDC_DESC_VALUE2                 2650
#define IDC_DESC_VALUE3                 2651
#define IDC_DESC_VALUE4                 2652
#define IDC_DESC_VALUE5                 2653
#define IDC_DESC_VALUE6                 2654
#define IDC_LABEL_VALUE1                2655
#define IDC_LABEL_VALUE2                2656
#define IDC_LABEL_VALUE3                2657
#define IDC_LABEL_VALUE4                2658
#define IDC_LABEL_VALUE5                2659
#define IDC_LABEL_VALUE6                2660
#define IDC_SPELL_LIST                  2661
#define IDC_CHOOSE1                     2662
#define IDC_CHOOSE2                     2663
#define IDC_SKILLS_LIST                 2664
#define IDC_CHOOSE3                     2665
#define IDC_ADD                         2666
#define IDC_CHOOSE4                     2667
#define IDC_EDIT                        2668
#define IDC_CHOOSE5                     2669
#define IDC_DELETE                      2670
#define IDC_DAMAGE                      2671
#define IDC_CHOOSE6                     2672
#define IDC_WEAR_OFF                    2673
#define IDC_DICE                        2674
#define IDC_HIT_CHAR                    2675
#define IDC_VALUE                       2676
#define IDC_FLAGS_SUMMARY               2677
#define IDC_HIT_VICT                    2678
#define IDC_SAVES                       2679
#define IDC_EDIT_PROGRAM                2680
#define IDC_HIT_ROOM                    2681
#define IDC_DIFFICULTY                  2682
#define IDC_COMMANDS_LIST               2683
#define IDC_MISS_CHAR                   2684
#define IDC_PARTICIPANTS                2685
#define IDC_MISS_VICT                   2686
#define IDC_AFFECTS_LIST                2687
#define IDC_MISS_ROOM                   2688
#define IDC_SOCIALS_LIST                2689
#define IDC_DIE_CHAR                    2690
#define IDC_CHAR_NO_ARG                 2691
#define IDC_DIE_VICT                    2692
#define IDC_OTHERS_NO_ARG               2693
#define IDC_COMMAND_COUNT               2694
#define IDC_DIE_ROOM                    2695
#define IDC_CHAR_FOUND                  2696
#define IDC_SKILL_COUNT                 2697
#define IDC_IMM_CHAR                    2698
#define IDC_OTHERS_FOUND                2699
#define IDC_SOCIALS_COUNT               2700
#define IDC_IMM_VICT                    2701
#define IDC_VICT_FOUND                  2702
#define IDC_COMMANDS_FILE               2703
#define IDC_IMM_ROOM                    2704
#define IDC_CHAR_AUTO                   2705
#define IDC_BROWSE_COMMANDS             2706
#define IDC_OTHERS_AUTO                 2707
#define IDC_SKILLS_FILE                 2708
#define IDC_HIT_DEST                    2709
#define IDC_BROWSE_SKILLS               2710
#define IDC_SOCIALS_FILE                2711
#define IDC_BROWSE_SOCIALS              2712
#define IDC_SUGGEST_HIT                 2713
#define IDC_CONFIG_FILE                 2714
#define IDC_SUGGEST_AC                  2715
#define IDC_WRAP                        2716
#define IDC_BROWSE_CONFIG               2717
#define IDC_FIND_TYPE                   2718
#define IDC_XREF_LIST                   2719
#define IDC_SELECT_ALL                  2720
#define IDC_DESELECT_ALL                2721
#define IDC_ABOUT_TO_DELETE             2722
#define IDC_MOB_COUNT                   2723
#define IDC_NEW_LOW_MOB_VNUM            2724
#define IDC_NEW_HIGH_MOB_VNUM           2725
#define IDC_SELLING                     2726
#define IDC_ROOM_COUNT                  2727
#define IDC_WARN_VNUMS_OUT_OF_RANGE     2728
#define IDC_NEW_LOW_ROOM_VNUM           2729
#define IDC_FIND_TEXT                   2730
#define IDC_NEW_HIGH_ROOM_VNUM          2731
#define IDC_POLYMORPHED                 2732
#define IDC_OBJECT_COUNT                2733
#define IDC_WATCH                       2734
#define IDC_NEW_LOW_OBJECT_VNUM         2735
#define IDC_ADD_ITEM                    2736
#define IDC_NEW_HIGH_OBJECT_VNUM        2737
#define IDC_REMOVE_ITEM                 2738
#define IDC_ADD_MOB                     2739
#define IDC_ADD_OBJECT                  2740
#define IDC_REMOVE                      2741
#define IDC_EQUIP                       2742
#define IDC_GIVE                        2743
#define IDC_CHOOSE_KEY                  2744
#define IDC_CONDITIONS                  2745
#define IDC_AREA_TABS                   2746
#define IDC_TOTAL_ECONOMY               2747
#define IDC_NEIGHBOURS_LIST             2748
#define IDC_TEMPERATURE                 2750
#define IDC_PRECIPITATION               2751
#define IDC_WIND                        2752
#define IDC_COLUMN_COUNT                2752
#define IDC_COMMAND                     2754
#define IDC_OUTPUT                      2755
#define IDC_SHOW_EQUIPMENT              2756
#define IDC_WALKTHROUGH_HELP            2757
#define IDC_WEAR_LOCATION               2758
#define IDC_WEAR7                       2759
#define IDC_WEAR14                      2760
#define IDC_WEAR1                       2761
#define IDC_WEAR3                       2762
#define IDC_WEAR_GROUP                  2763
#define IDC_NO_WEAR_FLAGS               2765
#define IDC_OBJECT_TYPE                 2766
#define IDC_FIND                        2767
#define IDC_FIND_NEXT                   2768
#define IDC_FIND_WHAT                   2769
#define IDC_DEFENSES_LABEL              2770
#define IDC_AREA_TYPE                   2771
#define IDC_SAVE_PROGRAMS               2772
#define IDC_VERSION_LIT                 2773
#define IDC_MOBSIZE                     2775
#define IDC_REGISTRATION_MESSAGE        2776
#define IDC_DAMAGE_TYPE                 2776
#define IDC_LEVEL_LABEL                 2777
#define IDC_CONDITION_LABEL             2778
#define IDC_MATERIAL_LABEL              2779
#define IDC_EXIT_TABS                   2780
#define IDC_WEAR_LOCATION_LABEL         2781
#define IDC_SPEAKS_LABEL                2782
#define IDC_SPEAKING_LABEL              2783
#define IDC_WEIGHT_UNITS                2784
#define IDC_ITEM_LIST                   2785
#define IDC_WHERE_LABEL                 2786
#define IDC_WHAT_LABEL                  2787
#define IDC_CLAN_NAME_LABEL             2788
#define IDC_CLAN_NAME                   2789
#define IDC_HEAL_RATE_LABEL             2790
#define IDC_HEAL_RATE                   2791
#define IDC_MANA_RATE_LABEL             2792
#define IDC_MANA_RATE                   2793
#define IDC_TUNNEL_LABEL                2794
#define IDC_EDIT_NAMES                  2795
#define IDC_DAMAGE_TYPE_LABEL           2796
#define IDC_AC_LABEL                    2797
#define IDC_EDIT_SHORT_DESCRIPTION      2798
#define IDC_EXP_LABEL                   2798
#define IDC_EDIT_LONG_DESCRIPTION       2799
#define IDC_HEIGHT_LABEL                2799
#define IDC_WEIGHT_LABEL                2800
#define IDC_GENERATED_NAME              2801
#define IDC_TRY_AGAIN                   2802
#define IDC_ROOM                        2805
#define IDC_VNUM_TYPE                   2806
#define IDC_ENGINE_PREFS                2810
#define IDC_CK_EDIT_WINDOW              2811
#define IDC_CK_AREA_CHECK               2812
#define IDC_CK_HELP                     2813
#define IDC_MOB_NAME                    2814
#define IDC_MOB_SHORT                   2815
#define IDC_MOB_LONG                    2816
#define IDC_MOB_DESC                    2817
#define IDC_OBJ_NAME                    2818
#define IDC_OBJ_SHORT                   2819
#define IDC_OBJ_LONG                    2820
#define IDC_OBJ_ACTION_DESC             2822
#define IDC_ROOM_NAME                   2823
#define IDC_ROOM_DESC                   2824
#define IDC_ACCEPT_NAME                 2825
#define IDC_CK_VIEW                     2826
#define IDC_CK_EXIT_DESC                2827
#define IDC_EXTRA_DESC                  2828
#define IDC_SPELL_CHECK                 2830
#define IDC_FLAG_MEANINGS               2832
#define IDC_REGISTRATION_URL            2834
#define ID_REGISTER_SMAUG_EDITOR        32772
#define IDS_CANNOT_BE_BLANK             32773
#define IDS_MIN_STRING_SIZE             32774
#define IDS_PROPSHT_CAPTION             32775
#define ID_HELP_TIPOFTHEDAY             32776
#define ID_FILE_AREA_SUMMARY            32778
#define ID_VIEW_WARNINGS                32779
#define ID_AREA_DELETE_ITEM             32780
#define ID_AREA_ADD_ITEM                32781
#define ID_AREA_FIND                    32782
#define ID_AREA_FIND_NEXT               32783
#define ID_STATUS_MODIFIED              32784
#define ID_SKILLS_LOAD                  32787
#define ID_SKILLS_SAVE                  32788
#define ID_SKILLS_EDIT                  32789
#define ID_COMMANDS_LOAD                32790
#define ID_COMMANDS_SAVE                32791
#define ID_COMMANDS_EDIT                32792
#define ID_SOCIALS_LOAD                 32793
#define ID_SOCIALS_SAVE                 32794
#define ID_SOCIALS_EDIT                 32795
#define ID_SKILLS_CLOSE                 32796
#define ID_COMMANDS_CLOSE               32797
#define ID_SOCIALS_CLOSE                32798
#define ID_FILE_PREFERENCES             32799
#define ID_AREA_CHECK                   32800
#define ID_AREA_DUPLICATE_ITEM          32801
#define ID_AREA_RENUMBER                32802
#define ID_EDIT_IGNORE_VALIDATION_ERRORS 32803
#define ID_AREA_WALKTHROUGH             32807
#define ID_FILE_EXPORT_MUSH             32808
#define ID_FILE_IMPORT_ROM              32809
#define ID_FILE_IMPORT_SMAUG            32810
#define ID_MENUITEM32811                32811
#define ID_FILE_EXPORT_OTHER            32812
#define ID_EDIT_GENERATENAME            32813
#define ID_EDIT_RELOADNAMES             32814
#define ID_VIEW_REFRESH                 32815
#define ID_FILE_OPENAREALIST            32816
#define ID_WINDOW_CLOSEALL              32817
#define ID_AREA_CHECKALLAREAS           32818
#define ID_EDIT_GOTOVNUM                32819

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        247
#define _APS_NEXT_COMMAND_VALUE         32820
#define _APS_NEXT_CONTROL_VALUE         2836
#define _APS_NEXT_SYMED_VALUE           237
#endif
#endif
